// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CurrencyLayerRepository is an autogenerated mock type for the CurrencyLayerRepository type
type CurrencyLayerRepository struct {
	mock.Mock
}

// GetCurrency provides a mock function with given fields: currency, currencyBeer
func (_m *CurrencyLayerRepository) GetCurrency(currency string, currencyBeer string) ([]float64, error) {
	ret := _m.Called(currency, currencyBeer)

	var r0 []float64
	if rf, ok := ret.Get(0).(func(string, string) []float64); ok {
		r0 = rf(currency, currencyBeer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float64)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(currency, currencyBeer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
