name: Go

on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - master
      - develop
      - 'feature/**'
    types: [ opened, synchronize, reopened ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: "github.com/samuskitchen//*"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15

      - name: Configure git for private modules
        run: git config --global url."https://${TOKEN}:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Build
        run: go build ./...

      - name: Test
        run: go test -v -coverprofile=coverage.out -coverpkg=./application/... ./test/...

  sonarcloud:
    needs: build
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Download code coverage results
        uses: actions/checkout@v2
        with:
          name: code-coverage-report
          path: bin

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}